  - name: System setup | application packages | install applications
    tags: hyprland
    ansible.builtin.package:
      name:
        - fish
        - kitty
        - nano
        - neovim
        - fuzzel
        - qt5-wayland
        - qt6-wayland
        - dunst
        - libnotify
        - nwg-look
        - kvantum
        - fastfetch
        - bind
      state: latest

  - name: System setup | application packages | install packages | yay
    kewlfft.aur.aur:
      name: 
        - brave-bin
        - visual-studio-code-bin
        - raffi-bin
        - swww
        - hyprlock
        - hypridle
        - sddm-sugar-dark
        - signal-desktop
      state: latest
    become: true
    become_user: aur_builder
